# Generated by Django 6.0.3 on 2026-04-04 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_promocode_shippingrate_order_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=50)),
                ('concerns', models.JSONField(default=list)),
                ('age_range', models.CharField(max_length=20)),
                ('routine_level', models.CharField(max_length=20)),
                ('recommended_products', models.JSONField(default=list)),
                ('skin_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic peau',
                'verbose_name_plural': 'Diagnostics peau',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positif = gagné, négatif = utilisé')),
                ('source', models.CharField(choices=[('purchase', 'Achat'), ('review', 'Avis produit'), ('signup', 'Inscription'), ('referral', 'Parrainage'), ('redemption', 'Utilisation')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction fidélité',
                'verbose_name_plural': 'Transactions fidélité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Maison', help_text='Ex: Maison, Bureau, Famille', max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, default='', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse enregistrée',
                'verbose_name_plural': 'Adresses enregistrées',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
