# Generated by Django 6.0.3 on 2026-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diagnosticresult_loyaltytransaction_savedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, help_text="Désigne si l'utilisateur est un vendeur/partenaire"),
        ),
    ]
