# Generated by Django 6.0.3 on 2026-04-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe (DA)')], default='percentage', max_length=20)),
                ('discount_value', models.PositiveIntegerField(help_text='Valeur de la remise (% ou DA)')),
                ('min_order', models.PositiveIntegerField(default=0, help_text='Montant minimum de commande en DA')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = illimité')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code promo',
                'verbose_name_plural': 'Codes promo',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_code', models.CharField(max_length=5, unique=True)),
                ('wilaya_name', models.CharField(max_length=100)),
                ('standard_price', models.PositiveIntegerField(help_text='Prix livraison standard en DA')),
                ('express_price', models.PositiveIntegerField(help_text='Prix livraison express en DA')),
                ('standard_days', models.CharField(default='3-5 jours', help_text='Délai livraison standard', max_length=20)),
                ('express_days', models.CharField(default='24-48h', help_text='Délai livraison express', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarif de livraison',
                'verbose_name_plural': 'Tarifs de livraison',
                'ordering': ['wilaya_code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Montant de la remise en DA'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode'),
        ),
    ]
