# Generated by Django 6.0.3 on 2026-04-05 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_old_price_product_stock_productimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Partner qui vend le produit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
