# Generated by Django 6.0.3 on 2026-04-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('author', models.CharField(default='Équipe Hilytouch', max_length=200)),
                ('date', models.DateField()),
                ('read_time', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date'],
            },
        ),
    ]
